version: "3.9"

services:
  database:
    image: postgres:12-alpine
    container_name: backend_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
  api:
    build:
      context: .
    container_name: server
    ports:
      - '9090:9090'
    environment:
      DB_HOST: jdbc:postgresql://database:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: secret
